name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-13, windows-latest]
        include:
          - os: windows-latest
            arch: x64
          - os: macos-13
            arch: x64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: npm install
        timeout-minutes: 10
        env:
          npm_config_target: 10.4.7
          npm_config_arch: x64
          npm_config_target_arch: x64
          npm_config_disturl: https://electronjs.org/headers
          npm_config_runtime: electron
          npm_config_build_from_source: true

      - name: Rebuild Native Dependencies
        run: npm run rebuild
        env:
          npm_config_openssl_fips: ''
          HOME: ~/.electron-gyp

      - name: Get version and name from package.json
        id: get_version_name
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          name: Release ${{ env.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_openssl_fips: ''
